### ISSUE TITLE
api/actions/active_instances endpoint responds with 404

### ISSUE THREAD

**Issue by zelima** [MuhammadIsmailShahzad/ckanext-ckan_cluster#1]
The example from readme returns 404 Eg https://ckan-cloud-management.ckan.io/api/3/actions/active_instances (both logged in and anonimous)

**Comment by ismail-shahzad** [comment]
That is a typo. I am going to fix that in the README.rst

Its `/api/3/action/active_instances` -- `action` instead of `actions`

**Comment by ismail-shahzad** [comment]
FIXED
