### ISSUE TITLE
move this repo under datopian namesapce

### ISSUE THREAD

**Issue by zelima** [MuhammadIsmailShahzad/ckanext-ckan_cluster#3]
@MuhammadIsmailShahzad please ownership to datopian (and update cloud repo)

**Comment by ismail-shahzad** [comment]
Transfer initiated

![Screenshot from 2020-11-18 16-58-14](https://user-images.githubusercontent.com/57398621/99527895-51a21080-29bf-11eb-8539-0d3432204915.png)

TRANSFERRED
New url https://github.com/datopian/ckanext-ckan_cluster
